version: '3'

services:
  postgres:
    image: 'postgres:15.4'
    container_name: 'PostgresSQL'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'